### ISSUE TITLE
Decoder fails for some profiles

### ISSUE THREAD

**Issue by RaidFourms** [axiangcoding/wt-profile-tool#35]
On some profiles, in this case user id 9107392 (nick is "redsuit") the decoder fails, with the following callback:

```
Traceback (most recent call last):
  File "/Users/*/Downloads/wt-profile-tool-main/test.py", line 4, in <module>
    profile = wtpt.get_profile_by_userid("9107392")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/Downloads/wt-profile-tool-main/wt_profile_tool/main.py", line 71, in get_profile_by_userid
    profile = decode_profile_from_raw_bytes(response.content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/Downloads/wt-profile-tool-main/wt_profile_tool/decode/decoder.py", line 28, in decode_profile_from_raw_bytes
    base_info = parse_base_info(msg_json.get("1", {}))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/Downloads/wt-profile-tool-main/wt_profile_tool/decode/decoder.py", line 48, in parse_base_info
    nick=str(data.get("2")),
             ^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
``` 
Using other profiles, such as # 140510695 work fine.

This has also happened before the recent commit with more definitions.

**Comment by axiangcoding** [comment]
fix in v0.3.1
